### ISSUE TITLE
the public key size of Generated key pair

### ISSUE THREAD

**Issue by Copypeng** [ricmoo/GMEllipticCurveCrypto#16]
Hi

I generated a key pair of secp256r1.

and I found the length of the compressedPublicKey is 65 bytes.

this makes me confused. I think it should be 64 bytes before.

**Comment by ricmoo** [comment]
That is certainly weird. An uncompressed key should be 65 bytes and a compressed key should be 33 bytes.

What is the first byte? Compressed keys should start with a 0x02 or 0x03 and uncompressed keys should start with a 0x04.

**Comment by Copypeng** [comment]
I see, it should be 64 bytes and the 0x04  starting。Thanks.

**Comment by iDurian** [comment]
> I see, it should be 64 bytes and the 0x04 starting。Thanks.

你好，可以给个联系方式吗？咨询你一点iOS问题，谢谢🙏
