### ISSUE TITLE
Trying to use in generate key pair in swift, but key strings are empty and data is nil.

### ISSUE THREAD

**Issue by ismyhc** [ricmoo/GMEllipticCurveCrypto#21]
Hi,

Im trying to get up and running in a swift project. Im trying to generate a new keypair, but it doesnt seem to be generating anything. 

Any help would be much appreciated :)

```swift
if let gmec = GMEllipticCurveCrypto(curve: GMEllipticCurveSecp128r1) {
    print("PRIVATE\n")
    print(gmec.privateKeyBase64)  // empty string
    print("\n\nPUBLIC\n")
    print(gmec.publicKeyBase64) // empty string
    let publicKey = gmec.publicKey // nil
    let privateKey = gmec.privateKey // nil
}

```

**Comment by ricmoo** [comment]
I don't know the swift syntax, but that would just be the curve. Try calling the generateKeyPair on it?

**Comment by ismyhc** [comment]
@ricmoo Yes! My bad, I was using the constructor rather than calling the static function. Calling like below worked! Thanks for the quick reply!

```swift
GMEllipticCurveCrypto.generateKeyPair(for: GMEllipticCurveSecp128r1)
```
