### ISSUE TITLE
Creating Shared Secret from GMEllipticCurveCrypto using a public JWK EC key and private EC key

### ISSUE THREAD

**Issue by deepesh-vasthimal-cko** [ricmoo/GMEllipticCurveCrypto#30]
I am trying to create a shared secret using a private EC and public JWK EC key using GMEllipticCurveCrypto library for iOS. Currently the library supports creating shared secret using below methods and i have tried both and just crashes with same error which is invalid key. Can anyone please help me how to create a shared key using a private EC and public JWK EC key with or without use of GMEllipticCurveCrypto ?. I have seen several blogs no one has posted valid code yet below is what I am trying to do.

```
let ecPublicKeyJson =
            """
                    {
                        "kty":"EC",
                        "crv":"P-256",
                        "x":"2_v-MuNZccqwM7PXlakW9oHLP5XyrjMG1W9oHLP5Xy",
                        "y":"rm1ktLmFIsP2R0YyJGXtsCbaTUesUXtsCbaTUesUdf"
                    }
                    """
 let ecPublicKeyJsonData = ecPublicKeyJson.data(using: .utf8)
 let ecPublicKeyJsonBase64 = ecPublicKeyJsonData?.base64EncodedString()
 let keyPair = GMEllipticCurveCrypto.generateKeyPair(for: GMEllipticCurveSecp256r1)

 let sharedZ = keyPair.getSharedSecret(publicKeyBase64: ecPublicKeyJsonBase64!)
```

Error or Crash : Terminating app due to uncaught exception 'Invalid Key'

**Comment by leohyman** [comment]
尝试一下这个: https://github.com/wjmwjmwb/ECDHUtils-OC

**Comment by leohyman** [comment]
你好,我想问一下. 你的
 "x":"2_v-MuNZccqwM7PXlakW9oHLP5XyrjMG1W9oHLP5Xy"                       "y":"rm1ktLmFIsP2R0YyJGXtsCbaTUesUXtsCbaTUesUdf"
我用openssl生成的ecc 公私钥 进行ecdhe. 能请教一下吗?
