### ISSUE TITLE
Can`t verify ECDSA signature generated by Bouncycatle in Java

### ISSUE THREAD

**Issue by bpalermo** [ricmoo/GMEllipticCurveCrypto#8]
Hi,

I`m trying to verify a signature generate in Java using:

`- (BOOL)hashSHA256AndVerifyEncodedSignature: (NSData*)encodedSignature forData: (NSData*)data`

But,

`NSData *derDecodeSignature(NSData *der, int keySize)`

always returns `nil`.

I'm using `GMEllipticCurveSecp256r1` and my encoded signature size is 88 bytes.

Could you help me?

**Comment by ricmoo** [comment]
Can you send me a sample of the DER encoded signature data?

**Comment by bpalermo** [comment]
Private key:

```
NSString *base64PrivateKey = @"MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpNKIRjwaIiXJ5pwJ9OOOp6G/B8sDbp+7DhddU9CYpFegCgYIKoZIzj0DAQehRANCAATHa6ww/lM/vh2eSwE8/ss1vbd2Tj11aVbVSGk7c+wl5Cu2edn9tlMQjJFdy5aQVAlZjTxizCv3UfkOzJvJtuEG"
```

```
 (void)testCheckSignature
{
    GMEllipticCurveCrypto *crypto = [GMEllipticCurveCrypto cryptoForCurve:
                                     GMEllipticCurveSecp256r1];

    int bits = 256;
    int publicKeyLength = 1 + 2 * bits / 8;

    NSString *base64PublicKey = @"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEx2usMP5TP74dnksBPP7LNb23dk49dWlW1UhpO3PsJeQrtnnZ/bZTEIyRXcuWkFQJWY08Yswr91H5DsybybbhBg==";
    NSString *base64SignatureData = @"AAAAAAX14QAAAAAAAAAAAgBDYW1hcm90ZSBWSVAgICAgICAgICAgICAgICAgICACAAEAAGGoAAA=";
    NSString *base64Signature = @"MEYCIQD6E5rPHWWayzORpvYcomLhOlnjw4WBvEQQW1HOhAp0DQIhAMajvHNk+W+LpW3krSP8WIDbTZ9dL7J05WtlyTbW8xsz";

    NSData *decoded = [[NSData alloc] initWithBase64EncodedString:base64PublicKey options:0];
    crypto.publicKey = [decoded subdataWithRange:NSMakeRange([decoded length] - publicKeyLength, publicKeyLength)];

    NSData *signatureData = [[NSData alloc] initWithBase64EncodedString:base64SignatureData options:NSUTF8StringEncoding];

    NSData *signature = [[NSData alloc] initWithBase64EncodedString:base64Signature options:NSUTF8StringEncoding];

    XCTAssertTrue([crypto hashSHA256AndVerifyEncodedSignature:signature forData:signatureData]);
}
```

**Comment by ricmoo** [comment]
Thanks!

I've been trying to debug it, but the DER decode seems to be working with this sample. Can you send me the Java code that generates the signature and all that jazz? Maybe a sample private key too.

(One side note, that doesn't affect this example, but the constant `NSUTF8StringEncoding` isn't valid for the `initWithBase64EncodedString:options:` selector; the only valid option is `NSDataBase64DecodingIgnoreUnknownCharacters`)

**Comment by bpalermo** [comment]
Private key on previous comment

```
public byte[] signECDSA(PrivateKey privateKey, byte[] message)
            throws NoSuchProviderException, NoSuchAlgorithmException, InvalidKeyException, SignatureException {
        Signature signature = Signature.getInstance(SHA256withECDSA, BC);
        signature.initSign(privateKey, random);

        signature.update(message);
        return signature.sign();
    }
```

**Comment by bpalermo** [comment]
How could I set the GMEllipticCurveCrypto private key from DER encoded bytes?

**Comment by bpalermo** [comment]
I'm really sorry, just found my error. I was printing the wrong data for debuging... Now it works!

Thanks for your attention

**Comment by ricmoo** [comment]
Awesome! Glad you found the problem. :)

As for the setting private/public key from the output of Java's DER encoding, it bundles them up in a really weird way with a bunch of identifiers and the key as a bitfield. I need to get a code snippet posted to demonstrate how to extract the key, but in the meantime, the way you are doing it is the easiest:

```
NSData *key = [keyDer subdataWithRange:NSMakeRange([keyDer length] - keyLength, keyLength)];
```

For private keys: `keyLength = crypto.bits / 8`.

For compressed public keys: `keyLength = 1 + crypto.bits / 8`.

For uncompressed public keys: `keyLength = 1 + 2 * crypto.bits / 8`.

**Comment by bpalermo** [comment]
Could be useful

```
/**
 *  The public key DER encoded in base64
 */
@property (nonatomic, strong) NSString *encodedPublicKeyBase64;
```

```
- (void)setEncodedPublicKeyBase64:(NSString *)encodedPublicKeyBase64 {
    NSData *decoded = [[NSData alloc] initWithBase64EncodedString:encodedPublicKeyBase64 options:0];

    int keyLength = keyLength = 1 + 2 * self.bits / 8;
    NSData *publicKey = [decoded subdataWithRange:NSMakeRange([decoded length] - keyLength, keyLength)];
    [self setPublicKey:publicKey];
}
```

**Comment by ricmoo** [comment]
Keep in mind that will only work for uncompressed public keys...

Public Key (uncompressed): 1 + 2 \* self.bits / 2;
Public Key (compressed): 1 + self.bits / 8;
Private Key: self.bits / 8;

I should write a function that will decode the DER payload and use the bit string. Should be simple, just have to add support for ASN.1 identifiers and bit strings...
